version: '3'
services:
    nginx:
        restart: always
        image: nginx
        volumes:
            - /pzhuweb/nginx:/etc/nginx #/pzhuweb/nginx本机nginx目录, /etc/nginx为容器目录
            - /pzhuweb:/usr/share/nginx/html #映射nginx的网页目录到容器里
        ports:
            - 80:80
            - 443:443
        links:
            #建立连接,web容器就无需暴露端口出去
            - app
    app:
        #指定container的名称, 后续方便使用命令进入到容器内以及与nginx.conf相对应
        container_name: app
        #构建容器
        build: ./app/
        links:
          - mysql
        depends_on:
          - mysql
    mysql:
        image: mysql
        restart: always 
        container_name:  mysql
        volumes:
          - ./mysql:/var/lib/mysql
         ports:
            - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: "123456"
        
