version: '3'
services:
    nginx:
        restart: always
        image: nginx
        volumes:
            - /pzhuweb/nginx:/etc/nginx #/pzhuweb/nginx本机nginx目录, /etc/nginx为容器目录
            - /pzhuweb/html:/usr/share/nginx/html #映射nginx的网页目录到容器里
        ports:
            - 80:80
            - 443:443
        links:
            #建立连接,web容器就无需暴露端口出去
            - tomcat
            - app
    app:
        #指定container的名称, 后续方便使用命令进入到容器内以及与nginx.conf相对应
        container_name: app
        #构建容器
        build: ./app/
        ports:
            - 3000:3000 
    tomcat:
        container_name: tomcat
        restart: always
        image: tomcat
        volumes:
            - /pzhuweb/website:/usr/local/tomcat/webapps #映射一个web服务
        ports:
            - 8080:8080
    # apache:
    #     restart: always
    #     image: httpd
    #     volumes:
    #         - /pzhuweb/website/:/usr/local/apache2/htdocs/
    #     ports:
    #         - '8080:80'
