FROM node
ADD . /usr/src/app
WORKDIR /usr/src/app
RUN npm config set registry https://registry.npm.taobao.org/
RUN npm install 
RUN npm i -g pm2 --no-optional
EXPOSE 3000
CMD ["pm2-docker", "start", "--json", "process.json"]